apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: kustomization1
  namespace: gitops-flux-v2

commonLabels:
  app: hello-world

resources:
- deployment.yaml
- service.yaml
